[package]
name = "building-blocks2"
version = "0.1.0"
authors = ["Fuyang Liu <fuyangl@spotify.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.94"
serde_json = "1.0.40"
ron = "0.5.1"
bson = "0.13"
