(function() {var implementors = {};
implementors["kvs"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"kvs/struct.KvsClient.html\" title=\"struct kvs::KvsClient\">KvsClient</a>",synthetic:true,types:["kvs::client::KvsClient"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"kvs/struct.KvStore.html\" title=\"struct kvs::KvStore\">KvStore</a>",synthetic:true,types:["kvs::engines::kvs::KvStore"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"kvs/struct.KvStorePingCap.html\" title=\"struct kvs::KvStorePingCap\">KvStorePingCap</a>",synthetic:true,types:["kvs::engines::kvs_p::KvStorePingCap"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"kvs/struct.SledKvsEngine.html\" title=\"struct kvs::SledKvsEngine\">SledKvsEngine</a>",synthetic:true,types:["kvs::engines::sled::SledKvsEngine"]},{text:"impl&lt;E&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"kvs/struct.KvsServer.html\" title=\"struct kvs::KvsServer\">KvsServer</a>&lt;E&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;E: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a>,&nbsp;</span>",synthetic:true,types:["kvs::server::KvsServer"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"enum\" href=\"kvs/enum.KvsError.html\" title=\"enum kvs::KvsError\">KvsError</a>",synthetic:true,types:["kvs::error::KvsError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
